FROM node:16.19.0-alpine

WORKDIR /app

RUN mkdir -p /app

RUN apk add openssl1.1-compat openssl

COPY . /app


RUN yarn cache clean \ 
  rm node_modules/ \
  yarn install --frozen-lockfile \
  yarn prisma generate

COPY . .

EXPOSE 3000

CMD [ "yarn", "start:dev" ]