FROM node:18.13.0-alpine3.17

WORKDIR /app

RUN mkdir -p /app

RUN apk add openssl1.1-compat openssl \ yarn global add @nestjs/cli

COPY . /app


RUN yarn cache clean \ 
  rm node_modules/ \
  yarn install --frozen-lockfile \
  yarn prisma generate

COPY . .

EXPOSE 3000

CMD [ "yarn", "start:dev" ]